fix: vite 4 build, apostrophe handling
pressbooks/pressbooks-network-catalog pull request #220
Opened 2023-05-29 18:24 UTC by arzola

This PR fix #203 and #181 

I removed the unneeded filter_var for the request parameters those are already sanitized by Laravel's default sanitization methods and I added a couple of `stripslashes` to avoid having issues with items with apostrophes in the UI, the string will be sanitized in the wp:prepare method

How to test:

1. Test the build process works on dev and production mode. (modifying the value of) `IS_VITE_DEVELOPMENT` in `pressbooks-network-catalog.php`
2. Test adding an institution with apostrophes or any special character like `St. Angela's College` you should be able to filter by that institutions and the filter it should be applied and selected on the sidebar.
3. This PR also address the duplicated parameters on desktop (those are only the duplicated selects that we are using for mobile) I mean those are not harmful just annoying to see on desktop maybe

2023-05-29 18:26 UTC, arzola commented on package.json
> +    "build": "vite build",
Default mode is production in Vite 4

2023-05-29 18:26 UTC, arzola commented on src/BooksRequestManager.php
> +								$in .= $wpdb->prepare('%s,', stripslashes($filterValue));
prepare will sanitize the value before touch the DB

2023-05-29 18:27 UTC, arzola commented on src/CatalogManager.php
> +		return stripslashes($value);
Not needed to filter or escape attributes, Laravel is doing that on the request object and automatically is even adding slashes in quotes

2023-05-29 18:28 UTC, arzola commented on src/CatalogManager.php
> +		return stripslashes($value);
I removed the condition because the function signature says that always return an string

2023-05-29 18:29 UTC, arzola commented on src/PressbooksNetworkCatalog.php
> +			if (isset($manifest['assets/css/app.css'])) {
Vite 4 is not processing css files that were imported through the js entry file

2023-05-29 18:30 UTC, arzola commented on src/Validators/InArrayValidator.php
> +			$data = array_map(static fn ($value) => stripslashes($value), $data);
We need to remove sanitization slashes before comparing with the values stored in the allowed values

2023-05-29 20:09 UTC, arzola commented on resources/views/components/search-input.blade.php
> +            name="search_term"
Wordpress doesn't like to use search get parameter when setup as homepage

2023-05-31 20:20 UTC, fdalcin requested changes
I tested this locally today, and for some reason I can't get `npm run dev` to work. If I set the `IS_VITE_DEVELOPMENT=true` and run `npm run dev` I get the break user interface. It works well with `npm run build` + `IS_VITE_DEVELOPMENT=false`, however.

Another thing that I noticed is that the duplicate parameter issue still happens for the `search_term` input, see below:
![image](https://github.com/pressbooks/pressbooks-network-catalog/assets/1761690/72a70770-0659-471e-a29a-fbd345c0bf7b)

In addition, I realized that using the mobile version does not work when searching because the desktop search term takes precedence. For example, this search should have returned me only one record but it's returning 4 instead
![image](https://github.com/pressbooks/pressbooks-network-catalog/assets/1761690/ead3d176-b0ee-4a2d-84a0-fcca18d3bd18)

The filter by institution with special characters is working as expected.

2023-05-31 23:41 UTC, fdalcin commented on vite.config.js
> +					css: resolve(__dirname + '/assets/css/app.css'),
```suggestion
          app: resolve(__dirname + '/assets/js/app.js'),
          css: resolve(__dirname + '/assets/css/app.css'),
```

2023-06-01 12:06 UTC, arzola commented
We can try to debug the `npm run dev` thing meanwhile I sent the fix to avoid dupes con desktop / mobile @fdalcin

2023-06-01 20:50 UTC, fdalcin approved these changes

2023-06-01 20:50 UTC, merged